### ISSUE TITLE
the counts of oral and poster error in KDD 2018

### ISSUE THREAD

**Issue by Hoyeop** [lixin4ever/Conference-Acceptance-Rate#14]
according to the KDD 2018 booklet, the counts of oral and poster are 107 and 74, respectively.
pls, fix the counts.
Official KDD 2018 booklet: https://www.kdd.org/kdd2018/files/KDD2018BookletShared.pdf

**Comment by lixin4ever** [comment]
Updated. Thank you for pointing out this.
