### ISSUE TITLE
IJCAI2019 accepted num is corrected to 850

### ISSUE THREAD

**Issue by ChijunZhang** [lixin4ever/Conference-Acceptance-Rate#15]

**Comment by lixin4ever** [comment]
According to the notification email, the total number of the accepted papers is 650. Is there any update on the submission system?

**Comment by ChijunZhang** [comment]
We have received the correction email just now.

**Comment by lixin4ever** [comment]
Thanks , I have just heard this message.  Is the paper conditioned on minor revisions equivalent to the accepted paper?

**Comment by ChijunZhang** [comment]
Yes, accepted 850 out of 4752 submissions  (including acceptance with minor revisions).

**Comment by lixin4ever** [comment]
Updated, thanks.
