### ISSUE TITLE
CIKM2019 acceptance rate update!

### ISSUE THREAD

**Issue by nh007cs** [lixin4ever/Conference-Acceptance-Rate#20]
The acceptance rate for CIKM2019 has been updated!

**Comment by lixin4ever** [comment]
Can you create a pull request? Or you can directly give the statistics here.

**Comment by nh007cs** [comment]
~1030 full papers were submitted to Research track, of which ~200 were accepted. The acceptance rate is 19.4%.

**Comment by lixin4ever** [comment]
Are 1030 and 200 the exact numbers?

**Comment by nh007cs** [comment]
Yes!
