### ISSUE TITLE
AAAI 2020 accept rates update

### ISSUE THREAD

**Issue by kvenux** [lixin4ever/Conference-Acceptance-Rate#22]
We had a record number of over 8,800 submissions this year. Of those, 7,737 were reviewed, and due to space limitations, we were only able to accept 1,591 papers, yielding an acceptance rate of 20.6%.

**Comment by lixin4ever** [comment]
Thanks. Maybe I should say congratulations to you.

**Comment by kvenux** [comment]
@lixin4ever Thank you. Your project helps a lot!
