### ISSUE TITLE
INTERSPEECH 2019 missing

### ISSUE THREAD

**Issue by msh9184** [lixin4ever/Conference-Acceptance-Rate#29]
Thank you for the good resource.

The information about the submission and acceptance rate of INTERSPEECH 2019 were reported in https://www.isca-speech.org/archive/Interspeech_2019/booklet.pdf, (page 10)

914 papers were accepted from 2180(or 1855) submissions.

thank you.

**Comment by lixin4ever** [comment]
Updated. Thanks for your information.
