### ISSUE TITLE
ICASSP'18 seems to be wrong

### ISSUE THREAD

**Issue by sn1ff1918** [lixin4ever/Conference-Acceptance-Rate#31]
Hi,

Thx for kind sharing, these data are quite useful!

However, from the table, 'ICASSP'18 | 49.7% (1406/2929)' seems to be wrong. 1406/2929=48.0%.
The total # of submit should be 2829 or 2830. And the acceptance rate should still be 49.7%.

Best regards

**Comment by lixin4ever** [comment]
Fixed. Thanks for your information.
