### ISSUE TITLE
interspeech 2020 accentance rate

### ISSUE THREAD

**Issue by chanwcom** [lixin4ever/Conference-Acceptance-Rate#35]
Interspeech 2020 acceptance rate was 47 %. It was mentioned in the acceptance/rejection decision e-mail from the committee.

You may find relevant information from the following links:

https://github.com/nay0648/bssaec2020
https://www.a.cs.okayama-u.ac.jp/~hara/news/2020/0725_accepted_INSTERSPEECH2020.html
https://web.wakayama-u.ac.jp/~irino/Papers/IntConfRev.html

**Comment by lixin4ever** [comment]
Thanks for your information.
