### ISSUE TITLE
NAACL21

### ISSUE THREAD

**Issue by wjczf123** [lixin4ever/Conference-Acceptance-Rate#41]
NAACL-HLT 2021 received 1797 submissions–a record for our conference! We accepted 477 papers, including 350 long and 127 short, for an overall acceptance rate of 26%. 

The acceptance rate for long papers was higher than short papers (28% vs. 23%), although this gap was smaller than in other recent conferences at least in part due to minor but explicit rebalancing done the the PC chairs.

**Comment by lixin4ever** [comment]
Updated. Thanks for your help.

**Comment by wjczf123** [comment]
No problem.
