### ISSUE TITLE
CVPR total accepted number incorrect?

### ISSUE THREAD

**Issue by DBWangWei** [lixin4ever/Conference-Acceptance-Rate#7]
(at least) CVPR18 & 19's total accepted numbers are incorrect? 

CVPR18: 70 + 244 + 685 = 999
CVPR19: posters alone is 1300.

**Comment by lixin4ever** [comment]
**UPDATED**
For CVPR 2018: the number of poster papers should be 224 (I have double-checked the proceedings) 
for CVPR 2019: still waiting for the official proceedings. If you know the details ,feel free to create a pull request.

**Comment by skrish13** [comment]
this is fixed and can be closed..
